// Regenerate typed ABI consts from the Foundry build artifacts.
// Run: node scripts/gen-abis.mjs   (after `forge build` in ../contracts)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "../../contracts/out");
const DEST = join(__dirname, "../lib/abis");

const CONTRACTS = [
  "MockUSDC",
  "CardNFT",
  "ChipNFT",
  "PackSale",
  "Marketplace",
  "RentalMarket",
  "GameRegistry",
  "ScoreOracle",
  "ContestEscrow",
  "InsurancePool",
  "SeasonLeaderboard",
];

if (!existsSync(OUT)) {
  console.error(`Artifacts not found at ${OUT}. Run \`forge build\` in ../contracts first.`);
  process.exit(1);
}
mkdirSync(DEST, { recursive: true });

const index = [];
for (const name of CONTRACTS) {
  const artifactPath = join(OUT, `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;
  const varName = `${name}Abi`;
  writeFileSync(
    join(DEST, `${name}.ts`),
    `// AUTO-GENERATED by scripts/gen-abis.mjs — do not edit by hand.\n` +
      `export const ${varName} = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
  index.push(`export { ${varName} } from "./${name}";`);
  console.log(`wrote lib/abis/${name}.ts`);
}
writeFileSync(join(DEST, "index.ts"), index.join("\n") + "\n");
console.log("wrote lib/abis/index.ts");
